//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProprioInfini
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ville
    {
        public Ville()
        {
            this.Adresses = new HashSet<Adresse>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public System.Data.Spatial.DbGeography GeoLocation { get; set; }
    
        public virtual ICollection<Adresse> Adresses { get; set; }
    }
}
