//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProprioInfini
{
    using System;
    using System.Collections.Generic;
    
    public partial class Villes_prof
    {
        public int ville_id { get; set; }
        public string nom { get; set; }
        public System.Data.Spatial.DbGeography geometrie { get; set; }
    }
}
